-   id: pretty-shell
    name: pretty-shell
    description: Make shell scripts pretty
    entry: pre-commit/pretty-shell.sh
    language: script
    files: (\.sh|\.zsh\.ksh)$
-   id: pretty-c
    name: pretty-c
    description: Make C source pretty
    entry: pre-commit/pretty-c.sh
    language: script
    files: (\.c|\.cpp|\.h|\.hpp)$
